const positiveWords = [
    "Absolutely",
    "Amazing",
    "Accepted",
    "Acclaimed",
    "Appreciate",
    "Beautiful",
    "Believe",
    "Certain",
    "Completely",
    "Creative",
    "Definitely",
    "Delight",
    "Easy",
    "Ecstatic",
    "Email",
    "Enjoy",
    "Essential",
    "Excellent",
    "Exceptional",
    "Exciting",
    "Expert",
    "Exquisite",
    "Fabulous",
    "Fantastic",
    "Fascinating",
    "Fair",
    "Favorite",
    "Familiar",
    "Friendly",
    "Generous",
    "Genius",
    "Great",
    "Ideally",
    "Impressive",
    "Interesting",
    "Marvelous",
    "Memorable",
    "Outstanding",
    "Positive",
    "Quickly",
    "Recommend",
    "Renowend",
    "Resolved",
    "Sensational",
    "Skillful",
    "Splendid",
    "Superb",
    "Terrific",
    "Thriving",
  ];
  
  const phrases = [
    "I'm here to help you with this issue. Let me see if I can find a solution.",
    "I'm going to take a closer look and see if I can identify the problem you're experiencing.",
    "I'm going to check a few things on my end and see if I can find a resolution.",
    "Don't worry, we'll get this issue sorted out together. Let's see what we can do.",
    "I appreciate your patience while I work on finding a solution for you.",
    "I'm committed to helping you resolve this issue. Let me see what I can do.",
    "I'm going to do some further investigation and get back to you with more information.",
    "I'm sorry for any delay. I'm actively working on finding a resolution for you now.",
    "Let me see if I can find a workaround for the problem you're experiencing.",
    "I'm going to check with my team and see if anyone has encountered this issue before.",
    "We're going to get this issue resolved as quickly as possible. Let me see what I can do.",
    "I apologize if this has caused any frustration. I'm going to do my best to find a solution.",
    "We want to make sure this issue is resolved as soon as possible. Let me see what I can do.",
    "I'm going to consult some resources and see if I can find a solution for you.",
    "I understand your concern. Let me see if I can find a way to resolve this for you.",
    "I'm going to check on the status of this issue and get back to you with an update.",
    "I appreciate your patience while I work on finding a resolution for you.",
    "I'm going to try a few different things to see if we can get this issue resolved for you.",
    "I understand how disruptive this can be. Let me see what I can do to help.",
    "I'm going to check our system logs and see if there's any information there that might be helpful in resolving this issue.",
    "I'm going to do some more digging and see if I can find a solution for you.",
    "I'm going to check with our support team and see if anyone has encountered this issue before and found a solution.",
    "I'm going to do some more research and get back to you as soon as I have more information.",
    "Absolutely, we can help you with that issue.",
    "Amazing, let's get that problem resolved for you.",
    "I completely understand your concern. We'll get it fixed.",
    "Don't worry, I'm here to help you. Let's get creative and find a solution.",
    "Definitely, I can assist you with that.",
    "Delighted to help you with any technical issues you're experiencing.",
    "I'll make this process easy for you.",
    "Ecstatic to assist you with your technical needs.",
    "Excellent, I'll take care of that for you.",
    "We have exceptional skills in resolving technical issues.",
    "Exciting to help you with your technical troubles.",
    "We're experts in the field of technical support.",
    "Our technical support is exquisite, let us assist you.",
    "Fantastic, we'll get that issue resolved for you.",
    "We're familiar with all types of technical issues, I'll be happy to help you.",
  ];
